### ISSUE TITLE
Add abilities and items.

### ISSUE THREAD

**Issue by ReallyCoolName** [SimonMossmyr/Enfo-MTE#13]
Hello Simon! this may not be the ideal place to put this, but it's the only way I can find to contact you.

I love this game, and even though it's not very popular atm, I'd love to work on it a bit if you're in.

My only complaint about the game is that it gets kind of boring if it goes on for too long. Playing with and against decent players means the game can go on for a while unless we play on nightmare/hell, which almost never happens.

I had some ideas:
1. Adding abilities that are shared across ALL heroes of a certain type (ex. all support heroes will have the same one, but different from the one all spellcasters have etc.)
2. Adding inventory slots (add an item which every person can only have 1 of, which adds a few inventory slots), buyable spells (one time use/learnable), maybe scaling the spells up a tiny bit so spellcasters won't be so useless in late game...

Almost all of these things, though, would require integrating some system to extend the inventory and replace the normal ability mechanism (which don't allow for more than 5 learnable abilities for heroes), which wouldn't be easy. Such systems exist, but the one I'm currently trying to understand isn't trivial to understand and has a few limitations (which I hope I can fix)

**Comment by SimonMossmyr** [comment]
One of the points of making this map a GitHub repository (rather than a `.w3x` file uploaded to Epic War) was to make people like you able to contribute easier. If you follow the instructions on the [Wiki](https://github.com/SimonMossmyr/Enfo-MTE/wiki) for opening, editing, and saving, you can implement these ideas yourself, then open a pull request and I'll have a look at it. If I don't like your ideas, you can give me the finger and make your own version by simply forking the project and calling it something else (Enfo's MT Even More Extended Edition?).

That said, here are my thoughts on your suggestions:

1. Why would this make the game less boring if it goes on for too long?
2. Can you elaborate further on more inventory slots? I don't understand.
3. Balancing is always welcome, but come with specific complaints like "Entropist's hurl rock deals too little damage between levels 5-10."
